version: 1
toolImage: artcsp-docker.ara-artifactory.volvocars.biz/vcc/common-build-agent:0.20.0
build:
  steps:
    - type: compose
      nodes:
        dev:
          dependsOn:
            - redis
          image: artcsp-docker.ara-artifactory.volvocars.biz/vcc/common-build-dev:0.7.0
          internalPorts: []
        redis:
          dependsOn: []
          image: redis:6.2-alpine
          internalPorts:
            - 6379
      commands:
        - cmd: npm --prefix backend install && npm --prefix backend run test && npm
            --prefix backend run build
          node: dev
        - cmd: npm --prefix frontend install && npm --prefix frontend run build
          node: dev
    - name: vcc/common-build-backend
      type: build
      file: docker/Dockerfile
      target: backend
    - name: vcc/common-build-frontend
      type: build
      file: docker/Dockerfile
      target: frontend
