toolImage: artcsp-docker.ara-artifactory.volvocars.biz/vcc/common-build-agent:0.9.0
version: 1
build:
  steps:
    - type: compose
      nodes:
        dev:
          image: artcsp-docker.ara-artifactory.volvocars.biz/vcc/common-build-dev:0.5.0
          dependsOn:
            - redis
          internalPorts: []
          startCmd: null
        redis:
          image: redis:6.2-alpine
          dependsOn: []
          internalPorts:
            - 6379
          startCmd: null
      commands:
        - cmd: npm --prefix backend install && npm --prefix backend run build 
          node: dev
        - cmd: npm --prefix frontend install && npm --prefix frontend run build 
          node: dev
    - type: build
      name: vcc/common-build-backend
      file: docker/Dockerfile
      target: backend
    - type: build
      name: vcc/common-build-frontend
      file: docker/Dockerfile
      target: frontend
