services:
  backend:
    image: common-build-dev:latest
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/backend:/work
      - logvolume01:/var/log
      - /tmp:/cache
    command: sleep infinity
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT:
      REDIS_PASSWORD:
      APP_NODE_ID: local-dev
      FRONTEND_URL: http://localhost:4000
    links:
      - redis
    depends_on:
      - redis
    container_name: backend
  frontend:
    image: common-build-dev:latest
    ports:
      - "4000:3000"
    volumes:
      - ${PWD}/frontend:/work
      - logvolume01:/var/log
    command: sleep infinity
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
    links:
      - backend
    depends_on:
      - backend
    container_name: frontend
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    container_name: redis
volumes:
  logvolume01: {}
