#!/bin/bash

export AZURE_AD_USER=<VCC-EMAIL>
export AZURE_PASSWORD=<CDSID_PASSWORD>
export AZURE_SUBSCRIPTION_ID="747dd2b4-2193-416e-b33d-146d6f9b6292"
export VAULT_TOKEN=<VAULT-TOKEN>
export VAULT_ADDR="https://winterfell.csp-dev.net"
