services:
  service:
    image: common-build:latest
    ports:
      - "3000:3000"
    volumes:
      - logvolume01:/var/log
    command: npm --prefix /app run start:prod
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/VCC-Root-CA-G2.crt
    links:
      - redis
    depends_on:
      - redis
    privileged: true
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
volumes:
  logvolume01: {}
